# Generated by Django 2.0 on 2017-12-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(max_length=9, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=12, unique=True)),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
    ]
